name: Check README.md

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'src/pages/index.mdx'
      - 'src/content/notes/**'
      - 'README.md'
  push:
    branches:
      - main
    paths:
      - 'src/pages/index.mdx'
      - 'src/content/notes/**'
      - 'README.md'

jobs:
  check-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Generate README
        run: pnpm update-readme

      - name: Check if README is up to date
        run: |
          if ! git diff --exit-code README.md; then
            echo "❌ README.md is not up to date!"
            echo "Please run 'pnpm update-readme' and commit the changes."
            exit 1
          else
            echo "✅ README.md is up to date!"
          fi
